### ISSUE TITLE
Improve Mac specific installation+debug documentation.

### ISSUE THREAD

**Issue by mac4kent** [hlorus/CAD_Sketcher#244]
### Contact Details

N/A

### Description

A bug happened!Look at picture they are wrong!
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/4253305/183761918-fe803201-0852-4b25-b141-fc878aba73d1.png">

Mac/Linux will not merge and not work.
They did give us link. https://hlorus.github.io/CAD_Sketcher/advanced/#console-output
Blender.app is NOT INSTALL. Only way drag app into Application folder. 
See picture. 
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/183762301-e0148ead-0004-495d-b0af-a80fac6b7f3c.png">

Linux/Windows is merge yes install Blender.exe only.
Mac must separate from Linux and separate from Windows.

### Addon Version

N/A

### Blender Version

3.2.2

### What platform are you running on?

Mac OSX

**Comment by amrsoll** [comment]
Would you like to write a paragraf to improve the Mac instructions to install?

**Comment by mac4kent** [comment]
What is improve , instructions ?
I am not good english text only I am full deaf and low vision.

**Comment by mac4kent** [comment]
@amrsoll

**Comment by KeithSloan** [comment]
Only vaguely related but I tried to install CAD-Sketcher and am failing at the first hurdle(s).

Trying to follow the instructions at https://hlorus.github.io/CAD_Sketcher/installation/

Okay I click on the "Zip Archive" but being on a Mac this automatically gets expanded in $HOME/Downloads.
Okay I use compress to create a zip file and then I think I am able to install the Addon.

I assume it is not working because I do not have blender with solverspace installed.
( In the past I have installed solverspace as an app I assume from a dmg but it was some time ago )

The instructions say
It's recommended to use the addon with Blender installed from the official website.
What does that mean? I have to install a copy of Blender with solverspace already installed or just
that blender needs to have been installed from official website?

Then it gives the option Install from PyPi - Press. "Install from PyPI" but I see nothing like that to press.
Try manually installing with pip install py-slvs. Restart Blender but no solverspace in Bender Preferences.

I am obviously too dumb for modern software.

**Comment by hlorus** [comment]
The installation guide already has a note "do not unpack it after downloading". Should that be expanded to say that it might have to be re-zipped?

**Comment by edgimar** [comment]
> The installation guide already has a note "do not unpack it after downloading". Should that be expanded to say that it might have to be re-zipped?

Yes, that would make sense to include.  Also, for me using the install from PyPI button worked, but after it was installed, I needed to restart Blender for it to be recognized.

**Comment by hlorus** [comment]
I hope this is clear enough: https://github.com/hlorus/CAD_Sketcher/pull/340

> Also, for me using the install from PyPI button worked, but after it was installed, I needed to restart Blender for it to be recognized.
There should already be a massage when this operator finishes which says to restart blender
