### ISSUE TITLE
[BUG]Distance constraint does not work between selected elements

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [hlorus/CAD_Sketcher#279]
### Contact Details

antoniocaroppos@gmail.com

### Description

I am trying to create a distance constraint between a line and a point.
Here is a video:

https://www.youtube.com/watch?v=Yl-TdMB93OQ

As you can see, the distance appears not between the selected elements but somewhere else.

Here is the blend file:
[intelligazethalter1.zip](https://github.com/hlorus/CAD_Sketcher/files/9470820/intelligazethalter1.zip)

### Addon Version

0.25

### Blender Version

3.25

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
In the video it seems that you've selected the circle instead of the point...

Anyway this is expected behavior since it's supported to add a distance on a single line. If you specifically want to add a constraint between the line and a point you can use a different selection paradigm like described here: https://hlorus.github.io/CAD_Sketcher/interaction_system/
