### ISSUE TITLE
Constraint visibility

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#47]
Allow user to handle display of constraints as they can be in the way sometimes.

- [ ] Add a global constraints display toggle to hide all constraints
- [ ] Add visibility property to constraint types similar to the entity's "visible" property

**Comment by hlorus** [comment]
@TheMakerTales not quite sure if this intends to add a global " show constraints" toggle or a per constraint toggle or both...?

**Comment by TheMakerTales** [comment]
@hlorus I think that both would be great at minimum individually.
and a little bit of feature creep here but I also have a feeling that a way of hiding all "lines" and all "construction lines" with a toggle would be interesting. 

I say this because while making this there was a lot of manual hiding of construction lines and lines to be sure I was clicking the constraining to the right thing. 

![Trim_Temp_Workaround](https://user-images.githubusercontent.com/103122109/167367867-a5ed75e3-ad16-4318-9ffe-9b8554f4d45f.jpg)

**Comment by exegetor** [comment]
Blender does have a "hide gizmo" button at top of 3dview.  shortcut is ctrl-`
Maybe we just need to put that in the documentation, since it isn't going to be obvious to a new user.

**Comment by TheMakerTales** [comment]
@exegetor I have a feeling in the next 2 weeks this might be sorted out tho as it has been commissioned out to a dev I work with quite a bit.
