### ISSUE TITLE
Sketch bevel tool

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#51]
Add a new tool which allows the user to put an arc between two existing segments (line / arc). The tool should find the correct placement for the arc's center and connection points to minimize jumping of the geometry when the solver runs.
Next it should trim the existing segments to the position of the connection points while keeping all existing constraints of the segments intact.
Finally it should add the arc and the tangential constraints.

This is probably best added as a statefull operator, see it's definition in operator.py.

**Comment by Intuos5** [comment]
In CAD software, I use the chamfer tool with a distance set to 0 on both ends to let two lines meet at their endpoint. Perhaps such a thing could be part of the bevel tool (considering the bevel tool can do both chamfers and fillets)?

**Comment by TheMakerTales** [comment]
I'm been thinking about what this tool could look like and I thought I would just put down a few things in here for food for thought. 

Personally, I really like the Bevel / Fillet tool of Plasticity:
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/103122109/176426583-b1293593-012c-4ece-8e8c-82cecca57b7c.gif)

I was thinking that this is how things could look like once made but the one limiting factor if we hide the constraints is what happens when users want to me "uneven" bevels and chamfers. Should that be part of the tool or a completely different issue as most use cases are looking for even bevels and chamfers...

Personally, I think exposing the constraints driving the chamfer and bevel to be a good thing as this way there is the flexibility to edit and hide them later if you don't want them cluttering up your view.
<img width="956" alt="Capture" src="https://user-images.githubusercontent.com/103122109/176427261-ad51a395-9340-403f-84fc-41f7d73063b7.PNG">

<img width="892" alt="Capture2" src="https://user-images.githubusercontent.com/103122109/176427276-977d1f4a-a2ad-4c14-835e-099dc6f0ddc3.PNG">

**Comment by Intuos5** [comment]
I would prefer to have a clean view of the chamfer/ bevel during its creation, but would like to have the flexibility to edit the constraints afterwards. Ideally, it has a flexible input, so just like Blender's bevel, where you are not forced to type in a radius beforehand. 
For chamfers, distance on both ends are nice, as are angle + distance. I think both methods should then create different constraints. The tool could be modal, so that you can tweak either end through a hotkey press/ modifier hold.
Just some initial thoughts on the matter.

**Comment by Intuos5** [comment]
The 0.25 bevel tool looks good! I would like to assign a radius constraint on the fly though. So after picking the two lines to bevel,  I would want to type in a radius, hit enter or click to confirm. Since the value is typed-in, it should also create a radius constraint with the same value. Hope this will alsi be considered 😉

**Comment by hlorus** [comment]
Entering a value is already supported, a constraint isn't auto created yet tho. There are some tools that do add a constraint when an exact value is typed in so it's definitely possible.

**Comment by hlorus** [comment]
Closed by 7a2a98adbd3f57dcf47c0326151d18fe53d92d76
