### ISSUE TITLE
Prompt user to restart blender after installing solver via pip

### ISSUE THREAD

**Issue by SupinePandora43** [hlorus/CAD_Sketcher#75]

**Comment by TheMakerTales** [comment]
I'm not too sure about this one. As it's not always needed. It's very dependent on the user's pip setup and os. Currently, there is also a built-in prompt at the bottom "warring" message letting users know: "Package should be available but cannot be found, check console for detailed info. Try restarting blender, otherwise get in contact."

**Comment by amrsoll** [comment]
I think it is a generaly good idea that - if we do already show that warning message - to have a <kbd>Restart Blender</kbd> button.

**Comment by hlorus** [comment]
Thanks for the report. With blender 4.20 CAD Sketcher is installed as an extension which brings support for pip dependencies. Blender will install the correct solver module when the extension is installed.
